wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.8
    cli_version: 0.16.5
    framework: huggingface
    huggingface_version: 4.40.0.dev0
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1712631634.0
    t:
      1:
      - 1
      - 11
      - 12
      - 49
      - 55
      2:
      - 1
      - 11
      - 12
      - 49
      - 55
      3:
      - 2
      - 23
      4: 3.11.8
      5: 0.16.5
      6: 4.40.0.dev0
      8:
      - 5
      13: linux-x86_64
